version: "2"
services:

  mongo:
    image: mongo
    restart: always
    container_name: app-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "iihtAdmin"
      MONGO_INITDB_ROOT_PASSWORD: "iihtpassword2022"
      MONGO_INITDB_DATABASE: "SkillTrackerDB"
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    container_name: app-mongo-gui
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://iihtAdmin:iihtpassword2022@mongo:27017"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "iihtAdmin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "iihtpassword2022"
    links:
      - mongo

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    container_name: app-kafka-gui
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    container_name: app-kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

  app-add-profile:
    build: ./add-profile-micro-service
    container_name: app-add-profile
    ports:
      - 8001:80
    environment:
      KAFKA_BROKER_URL: "kafka:29092"
      KAFKA_GROUP_ID: "add-profile-group"
      KAFKA_CONNECTION_TIMEOUT: 3000
      KAFKA_AUTHENTICATION_TIMEOUT: 1000
      KAFKA_RE_AUTHENTICATION_THRESHOLD: 10000
      MONGODB_URL: "mongo:27017"
      MONGO_INITDB_ROOT_USERNAME: "iihtAdmin"
      MONGO_INITDB_ROOT_PASSWORD: "iihtpassword2022"
      MONGO_INITDB_DATABASE: "SkillTrackerDB"
    links:
      - "mongo"
      - "kafka"
    depends_on:
      - "mongo"
      - "kafka"

  app-update-profile:
    build: ./update-profile-micro-service
    container_name: app-update-profile
    ports:
      - 8002:80
    environment:
      KAFKA_BROKER_URL: "kafka:29092"
      KAFKA_GROUP_ID: "update-profile-group"
      KAFKA_CONNECTION_TIMEOUT: 3000
      KAFKA_AUTHENTICATION_TIMEOUT: 1000
      KAFKA_RE_AUTHENTICATION_THRESHOLD: 10000
      MONGODB_URL: "mongo:27017"
      MONGO_INITDB_ROOT_USERNAME: "iihtAdmin"
      MONGO_INITDB_ROOT_PASSWORD: "iihtpassword2022"
      MONGO_INITDB_DATABASE: "SkillTrackerDB"
    links:
      - "mongo"
      - "kafka"
    depends_on:
      - "mongo"
      - "kafka"

  app-search-profile:
    build: ./search-profile-micro-service
    container_name: app-search-profile
    ports:
      - 8003:80
    environment:
      KAFKA_BROKER_URL: "kafka:29092"
      KAFKA_GROUP_ID: "search-profile-group"
      KAFKA_CONNECTION_TIMEOUT: 3000
      KAFKA_AUTHENTICATION_TIMEOUT: 1000
      KAFKA_RE_AUTHENTICATION_THRESHOLD: 10000
      MONGODB_URL: "mongo:27017"
      MONGO_INITDB_ROOT_USERNAME: "iihtAdmin"
      MONGO_INITDB_ROOT_PASSWORD: "iihtpassword2022"
      MONGO_INITDB_DATABASE: "SkillTrackerDB"
    links:
      - "mongo"
      - "kafka"
    depends_on:
      - "mongo"
      - "kafka"

  app-get-skill:
    build: ./get-skill-micro-service
    container_name: app-get-skill
    ports:
      - 8004:80
    environment:
      KAFKA_BROKER_URL: "kafka:29092"
      KAFKA_GROUP_ID: "get-skill-group"
      KAFKA_CONNECTION_TIMEOUT: 3000
      KAFKA_AUTHENTICATION_TIMEOUT: 1000
      KAFKA_RE_AUTHENTICATION_THRESHOLD: 10000
      MONGODB_URL: "mongo:27017"
      MONGO_INITDB_ROOT_USERNAME: "iihtAdmin"
      MONGO_INITDB_ROOT_PASSWORD: "iihtpassword2022"
      MONGO_INITDB_DATABASE: "SkillTrackerDB"
    links:
      - "mongo"
      - "kafka"
    depends_on:
      - "mongo"
      - "kafka"

  app-api-gateway:
    build: ./api-gateway-service
    container_name: app-api-gateway
    environment:
      KAFKA_BROKER_URL: "kafka:29092"
      KAFKA_CONNECTION_TIMEOUT: 3000
      KAFKA_AUTHENTICATION_TIMEOUT: 1000
      KAFKA_RE_AUTHENTICATION_THRESHOLD: 10000
      APP_GLOBAL_API_PREFIX: "skill-tracker/api"
      APP_GLOBAL_DEFAULT_VERSION: 1
      APP_GLOBAL_PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - "app-add-profile"
      - "app-update-profile"
      - "app-search-profile"
      - "app-get-skill"

  app-web:
    build: ./nx-web-monorepo
    container_name: app-web
    environment:
      API_BASE_URL: "/skill-tracker/api/v1/"
    ports:
      - 4200:80
    depends_on:
      - "app-api-gateway"
    links:
      - "app-api-gateway"
